services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - cd backend_graphql
  - docker --version # print the version for logging
  - docker build -t graphql .
  - docker tag graphql yunwei0219/graphql:latest
  - cd ../backend_login
  - docker build -t graphql-login .
  - docker tag graphql-login yunwei0219/graphql-login:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push yunwei0219/graphql
  - docker push yunwei0219/graphql-login